# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-28 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20170128_1537'),
        ('base', '0034_auto_20170124_0532'),
    ]

    operations = [
    ]
