# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-28 17:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 28, 12, 8, 35, 987434)),
        ),
    ]
